### PR TITLE
fix: refactor test so it works with Drupal 10.3

### LINKED ISSUE #40: Test failure CrossMenuAssignmentTest::testFormSubmission
```
Drupal\Tests\localgov_menu_link_group\Kernel\CrossMenuAssignmentTest::testFormSubmission
Failed asserting that an array is empty.

/var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:122
/var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:56
/var/www/html/web/modules/contrib/localgov_menu_link_group/tests/src/Kernel/CrossMenuAssignmentTest.php:78
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
```

### PR DESCRIPTION
**Pull request by millnut**
## What does this change?

This fixes #40 the failing test in this module, and the last failing PHPUnit test for the project repo 🎉

### CODE REVIEW

File: tests/src/Kernel/CrossMenuAssignmentTest.php [hunk 1]
```diff
@@ -38,11 +44,8 @@ protected function setUp(): void {
     $this->installEntitySchema('localgov_menu_link_group');
     $this->container->get('plugin.manager.menu.link')->rebuild();
 
-    $admin_user = User::create([
-      'name' => 'admin',
-      'mail' => 'admin@example.net',
-    ]);
-    $admin_user->addRole('administrator');
+    $admin_user = $this->createUser([], 'admin', TRUE, ['mail' => 'admin@example.net']);
```
Comment (ekes) [inline tests/src/Kernel/CrossMenuAssignmentTest.php:47]: Is EntityKernelTestBase just here for this?

Interested rather than bothered.

**Review by ekes — APPROVED** [review]
Fixes #40 as tests pass, looks fine, so happy.

File: tests/src/Kernel/CrossMenuAssignmentTest.php (hunk 1 above)
Comment (millnut) [reply tests/src/Kernel/CrossMenuAssignmentTest.php:47]: Yes and I believe some other things it does differently, trying the other testbase didn't seem to work with assigning roles correctly (at least in Drupal 10.3) until I did some digging around other contrib modules that seem to make similar changes
